import random

def recovery_passphrase():
    return generate_recovery_passphrase(word_list)

def generate_recovery_passphrase(word_list, num_words=10):
    """
    Génère une passphrase de récupération en choisissant aléatoirement des mots dans une liste fournie.
    :param word_list: Liste des mots parmi lesquels choisir.
    :param num_words: Nombre de mots à inclure dans la passphrase (défaut: 10).
    :return: Une chaîne de caractères contenant les mots choisis séparés par un espace.
    """
    if len(word_list) < num_words:
        raise ValueError("La liste de mots doit contenir au moins {} mots uniques.".format(num_words))
    selected_words = random.sample(word_list, num_words)
    passphrase = ' '.join(selected_words)
    return passphrase

word_list = [
"soleil", "lune", "étoile", "comète", "planète",
    "galaxie", "univers", "astéroïde", "nébuleuse", "quasar",
    "satellite", "orbite", "constellation", "télescope", "observatoire",
    "océan", "rivière", "montagne", "forêt", "désert",
    "chat", "chien", "oiseau", "éléphant", "lion",
    "pomme", "banane", "cerise", "datte", "figue",
    "voiture", "avion", "bateau", "vélo", "train",
    "chaise", "table", "fenêtre", "porte", "lit",
    "livre", "stylo", "papier", "ordinateur", "clavier",
    "musique", "peinture", "danse", "théâtre", "cinéma",
    "printemps", "été", "automne", "hiver", "saison",
    "matin", "midi", "soir", "nuit", "aube",
    "joie", "tristesse", "colère", "surprise", "peur",
    "blanc", "noir", "rouge", "bleu", "vert",
    "carré", "cercle", "triangle", "rectangle", "hexagone",
    "sucre", "sel", "épice", "amer", "acide",
    "chaud", "froid", "tiède", "gelé", "brûlant",
    "doux", "dur", "lisse", "rugueux", "mou",
    "haute", "basse", "moyenne", "gigantesque", "minuscule",
    "rapide", "lent", "agile", "maladroit", "vif",
    "fort", "faible", "puissant", "insignifiant", "robuste",
    "riche", "pauvre", "économique", "luxueux", "abordable",
    "ancien", "moderne", "futuriste", "historique", "daté",
    "quotidien", "occasionnel", "rare", "unique", "commun",
    "propre", "sale", "net", "taché", "immaculé",
    "amer", "doux", "salé", "épicé", "savoureux",
    "brillant", "mat", "transparent", "opaque", "réfléchissant",
    "lourd", "léger", "massif", "mince", "épais",
    "précis", "vague", "détaillé", "simplifié", "complexe",
    "clair", "confus", "évident", "obscur", "lumineux",
    "bruyant", "silencieux", "sonore", "muet", "assourdissant",
    "délicieux", "fade", "exquis", "nauséabond", "appétissant",
    "souple", "rigide", "flexible", "inflexible", "élastique",
    "optimiste", "pessimiste", "réaliste", "idéaliste", "cynique",
    "courageux", "peureux", "audacieux", "timide", "brave",
    "joyeux", "mélancolique", "heureux", "triste", "enthousiaste",
    "amical", "hostile", "chaleureux", "froid", "accueillant",
    "généreux", "avare", "charitable", "égoïste", "bienveillant",
    "intelligent", "sot", "sage", "naïf", "astucieux",
    "beau", "laid", "attrayant", "repoussant", "magnifique",
    "jeune", "vieux", "nouveau", "ancien", "éternel",
    "rapide", "instantané", "progressif", "lent", "graduel",
    "calme", "tempête", "paisible", "turbulent", "orageux",
    "sec", "humide", "mouillé", "aride", "saturé",
    "chaotique", "ordonné", "désorganisé", "structuré", "anarchique",
    "vibrant", "terne", "coloré", "monochrome", "vif",
    "sain", "malade", "robuste", "fragile", "vigoureux",
    "épais", "fin", "large", "étroit", "volumineux",
    "durable", "éphémère", "permanent", "temporaire", "persistant",
    "subtil", "évident", "implicite", "explicite", "nuancé",
    "pénétrant", "superficiel", "profond", "superficiel", "intense",
    "compétent", "incompétent", "capable", "incapable", "adroit",
    "loyal", "traître", "fidèle", "infidèle", "dévoué",
    "honnête", "malhonnête", "sincère", "trompeur", "authentique",
    "tolérant", "intolérant", "acceptant", "réfractaire", "ouvert",
    "curieux", "indifférent", "intrigué", "désintéressé", "fouineur",
    "enthousiaste", "apathique", "passionné", "indolent", "énergique",
    "confiant", "incertain", "assuré", "douteux", "convaincu",
    "déterminé", "hésitant", "résolu", "vacillant", "inébranlable",
    "inventif", "banal", "créatif", "stéréotypé", "original",
    "prudent", "imprudent", "méfiant", "téméraire", "circonspect",
    "économe", "prodigue", "sauvegardé", "dépensier", "prévoyant",
    "perspicace", "obtus", "clairvoyant", "myope", "discernant",
    "compréhensif", "incompréhensible", "perspicace", "obtus", "éclairé",
    "amoureux", "indifférent", "passionné", "froid", "affectionné",
    "dévoué", "négligent", "consacré", "désintéressé", "attaché",
    "motivé", "démotivé", "inspiré", "découragé", "stimulé",
    "respectueux", "irrespectueux", "poli", "impoli", "courtois",
    "rêveur", "réaliste", "idéaliste", "pragmatique", "visionnaire",
    "éloquent", "inarticulé", "convaincant", "vague", "persuasif",
    "réfléchi", "impulsif", "considéré", "précipité", "méditatif",
    "serein", "agité", "tranquille", "nerveux", "reposé",
    "fiable", "peu fiable", "digne de confiance", "suspect", "loyal",
    "énergique", "léthargique", "vital", "fatigué", "dynamique",
    "prospère", "défavorisé", "florissant", "en déclin", "réussi",
    "innovant", "traditionnel", "révolutionnaire", "conventionnel", "novateur",
    "équitable", "injuste", "impartial", "partial", "juste",
    "altruiste", "égoïste", "généreux", "égocentrique", "désintéressé",
    "persévérant", "inconstant", "tenace", "fugace", "obstiné",
    "souple", "inflexible", "adaptable", "rigide", "malléable",
    "équilibré", "déséquilibré", "harmonieux", "discordant", "stable",
    "poétique", "prosaïque", "lyrique", "banal", "expressif",
    "majestueux", "modeste", "grandiose", "simple", "imposant",
    "spirituel", "sérieux", "drôle", "grave", "amusant",
    "mystérieux", "clair", "énigmatique", "explicite", "occulte",
    "vénérable", "méprisable", "respecté", "détesté", "estimé",
    "puissant", "faible", "dominant", "soumis", "influent",
    "affamé", "rassasié", "avide", "satisfait", "insatiable",
    "humide", "sec", "mouillé", "aride", "damp",
    "brillant", "sombre", "lumineux", "obscur", "éclatant",
    "fragrant", "fétide", "parfumé", "malodorant", "odorant",
    "croustillant", "mou", "dur", "tendre", "ferme",
    "amer", "sucré", "acide", "salé", "piquant",
    "chaud", "froid", "tiède", "brûlant", "glacial",
    "énorme", "minuscule", "immense", "petit", "vaste",
    "ancien", "nouveau", "vieux", "récent", "primitif",
    "rapide", "lent", "véloce", "tardif", "prompt",
    "silencieux", "bruyant", "calme", "tumultueux", "paisible",
    "clair", "trouble", "transparent", "opaque", "limpide",
    "doux", "rugueux", "lisse", "épineux", "velouté",
    "léger", "lourd", "poids plume", "pondéreux", "aérien",
    "optimiste", "pessimiste", "positif", "négatif", "espérant",
    "courageux", "peureux", "brave", "timoré", "vaillant",
    "joyeux", "triste", "heureux", "mélancolique", "gai",
    "riche", "pauvre", "aisé", "dénué", "opulent",
    "sain", "malade", "vigoureux", "invalide", "robuste",
    "intelligent", "idiot", "brillant", "stupide", "avisé",
    "beau", "laid", "joli", "repoussant", "attrayant",
    "fort", "faible", "robuste", "débile", "puissant",
    "chaud", "froid", "brûlant", "gelé", "tiède",
    "sucré", "amer", "salé", "acide", "délicieux",
    "dur", "mou", "solide", "souple", "rigide",
    "rapide", "lent", "précipité", "tardif", "expéditif",
    "clair", "obscur", "lumineux", "sombre", "brillant",
    "haut", "bas", "élevé", "profond", "surélevé",
    "large", "étroit", "vaste", "serré", "spacieux",
    "plein", "vide", "rempli", "dépeuplé", "chargé",
    "neuf", "usé", "nouveau", "ancien", "flambant neuf",
    "propre", "sale", "net", "souillé", "immaculé",
    "doux", "fort", "léger", "intense", "faible",
    "précis", "imprécis", "exact", "vague", "détaillé",
    "près", "loin", "proche", "éloigné", "adjacent",
    "jeune", "âgé", "nouveau", "vieux", "juvénile",
    "frais", "rassis", "récent", "périmé", "nouveau",
    "calme", "agité", "tranquille", "perturbé", "serein",
    "facile", "difficile", "simple", "compliqué", "aisé",
    "lumineux", "obscur", "brillant", "sombre", "éclatant",
    "chaud", "froid", "ardent", "glacial", "tiède",
    "sec", "humide", "aride", "mouillé", "desséché",
    "public", "privé", "ouvert", "fermé", "communal",
    "fort", "faible", "sonore", "silencieux", "puissant",
    "début", "fin", "commencement", "achèvement", "ouverture",
    "victoire", "défaite", "succès", "échec", "triomphe",
    "ami", "ennemi", "compagnon", "adversaire", "allié",
    "amour", "haine", "affection", "aversion", "passion",
    "paix", "guerre", "tranquillité", "conflit", "harmonie",
    "richesse", "pauvreté", "abondance", "manque", "opulence",
    "sagesse", "folie", "connaissance", "ignorance", "érudition",
    "pouvoir", "impuissance", "domination", "soumission", "autorité",
    "liberté", "servitude", "indépendance", "contrainte", "émancipation",
    "courage", "lâcheté", "bravoure", "peur", "témérité",
    "joie", "tristesse", "bonheur", "douleur", "plaisir",
    "vie", "mort", "existence", "néant", "survie",
    "lumière", "ombre", "éclat", "ténèbres", "rayonnement",
    "eau", "feu", "terre", "air", "élément",
    "ciel", "enfer", "paradis", "abîme", "firmament",
    "ange", "démon", "saint", "pécheur", "divinité",
    "rêve", "réalité", "fantasie", "vérité", "illusion",
    "espoir", "désespoir", "aspiration", "résignation", "optimisme",
    "beauté", "laideur", "grâce", "défiguration", "splendeur",
    "force", "fragilité", "vigueur", "faiblesse", "énergie",
    "amitié", "inimitié", "camaraderie", "antipathie", "complicité",
    "connaissance", "méconnaissance", "savoir", "ignorance", "érudition",
    "patience", "impatience", "tolérance", "intolérance", "endurance",
    "confiance", "méfiance", "foi", "scepticisme", "crédulité",
    "vérité", "mensonge", "réalité", "fiction", "honnêteté",
    "justice", "injustice", "équité", "partialité", "droiture",
    "santé", "maladie", "bien-être", "affliction", "vitalité",
    "intelligence", "bêtise", "perspicacité", "naïveté", "acuité",
    "éducation", "ignorance", "apprentissage", "inculture", "savoir",
    "esprit", "corps", "âme", "matière", "conscience",
    "nature", "culture", "instinct", "éducation", "essence",
    "art", "science", "technologie", "littérature", "philosophie",
    "histoire", "géographie", "politique", "économie", "sociologie",
    "mathématiques", "physique", "chimie", "biologie", "informatique",
    "musique", "peinture", "sculpture", "danse", "cinéma",
    "poésie", "roman", "nouvelle", "théâtre", "essai",
    "architecture", "photographie", "bande dessinée", "design", "mode",
    "gourmet", "voyage", "aventure", "découverte", "exploration",
    "sport", "yoga", "méditation", "fitness", "athlétisme",
    "cuisine", "gastronomie", "pâtisserie", "vin", "brasserie",
    "écologie", "environnement", "développement durable", "recyclage", "conservation",
    "astronomie", "astrologie", "espace", "univers", "cosmos",
    "quantique", "relativité", "particule", "atome", "molécule",
    "robotique", "cybernétique", "intelligence artificielle", "nanotechnologie", "biotechnologie",
    "psychologie", "psychanalyse", "thérapie", "cognition", "émotion",
    "société", "communauté", "individu", "collectivité", "population",
    "culture", "tradition", "modernité", "avant-garde", "heritage",
    "langue", "dialecte", "idiome", "jargon", "argot",
    "religion", "spiritualité", "croyance", "athéisme", "agnosticisme",
    "éthique", "morale", "vertu", "vice", "principe",
    "loi", "règlement", "jurisprudence", "droit", "justice",
    "économie", "finance", "monnaie", "richesse", "pauvreté",
    "entreprise", "industrie", "commerce", "management", "marketing",
    "technologie", "innovation", "recherche", "découverte", "invention",
    "internet", "web", "réseau", "cyberspace", "virtualité",
    "média", "communication", "information", "presse", "journalisme",
    "santé", "médecine", "chirurgie", "pharmacie", "thérapie",
    "éducation", "enseignement", "apprentissage", "formation", "pédagogie",
    "famille", "amitié", "amour", "relation", "communauté",
    "jeu", "divertissement", "loisir", "hobby", "passetemps",
    "voyage", "tourisme", "expédition", "aventure", "exploration",
    "nature", "paysage", "faune", "flore", "biodiversité",
    "ville", "campagne", "urbanisme", "architecture", "infrastructure",
    "art", "culture", "création", "expression", "beauté",
    "science", "technologie", "innovation", "découverte", "recherche",
    "histoire", "patrimoine", "tradition", "mémoire", "archive",
    "philosophie", "pensée", "idée", "concept", "raisonnement",
    "littérature", "poésie", "roman", "nouvelle", "essai",
    "cinéma", "théâtre", "musique", "danse", "peinture",
    "photographie", "sculpture", "architecture", "design", "mode",
    "cuisine", "gastronomie", "vin", "recette", "alimentation",
    "sport", "fitness", "yoga", "course", "natation",
    "voyage", "aventure", "exploration", "tourisme", "expédition",
    "nature", "environnement", "écologie", "paysage", "faune",
    "société", "culture", "politique", "économie", "histoire",
    "science", "technologie", "mathématiques", "physique", "chimie",
    "art", "littérature", "musique", "cinéma", "théâtre",
    "philosophie", "psychologie", "sociologie", "anthropologie", "linguistique",
    "médecine", "biologie", "écologie", "géologie", "astronomie",
    "informatique", "robotique", "intelligence artificielle", "cybersécurité", "réseaux sociaux",
    "éducation", "enseignement", "apprentissage", "formation", "curriculum",
    "droit", "justice", "légalité", "éthique", "morale",
    "économie", "finance", "banque", "investissement", "marché",
    "entreprise", "management", "leadership", "innovation", "stratégie",
    "marketing", "publicité", "marque", "consommateur", "produit",
    "communication", "médias", "journalisme", "réseaux sociaux", "publicité",
    "culture", "tradition", "patrimoine", "identité", "diversité",
    "société", "communauté", "population", "démographie", "migration",
    "politique", "gouvernement", "démocratie", "élection", "parti",
    "international", "globalisation", "relations", "diplomatie", "conflit",
    "santé", "bien-être", "prévention", "maladie", "traitement",
    "environnement", "durabilité", "ressources", "conservation", "pollution",
    "technologie", "innovation", "numérique", "futurisme", "disruption",
    "éducation", "apprentissage", "compétences", "connaissances", "curiosité",
    "art", "créativité", "esthétique", "inspiration", "expression",
    "culture", "histoire", "tradition", "modernité", "patrimoine",
    "société", "communauté", "interaction", "inclusion", "égalité",
    "économie", "marché", "commerce", "finance", "prospérité",
    "politique", "gouvernance", "loi", "citoyenneté", "activisme",
    "science", "recherche", "découverte", "innovation", "expérimentation",
    "technologie", "numérique", "cyberspace", "robotique", "intelligence artificielle",
    "environnement", "écologie", "durabilité", "biodiversité", "conservation",
    "santé", "médecine", "bien-être", "prévention", "guérison",
    "éducation", "enseignement", "apprentissage", "formation", "savoir",
    "culture", "art", "littérature", "musique", "cinéma",
    "société", "communauté", "famille", "relations", "identité",
    "économie", "finance", "entreprise", "industrie", "marché",
    "politique", "gouvernement", "loi", "droit", "citoyenneté",
    "science", "technologie", "recherche", "innovation", "découverte",
    "environnement", "nature", "écologie", "durabilité", "ressources",
    "santé", "médecine", "nutrition", "sport", "bien-être",
    "éducation", "apprentissage", "formation", "compétences", "connaissance",
    "culture", "tradition", "histoire", "patrimoine", "art",
    "société", "démographie", "relations", "communauté", "diversité",
    "économie", "commerce", "finance", "investissement", "consommation",
    "politique", "démocratie", "élections", "gouvernance", "politiques",
    "science", "exploration", "expérimentation", "théorie", "pratique",
    "technologie", "innovation", "numérique", "informatique", "communication",
    "environnement", "climat", "conservation", "énergie", "durabilité",
    "santé", "prévention", "soins", "médecine", "psychologie",
    "éducation", "enseignement", "formation", "savoir", "pédagogie",
    "culture", "arts", "littérature", "musique", "théâtre",
    "société", "communauté", "relations humaines", "cohésion sociale", "solidarité",
    "économie", "gestion", "entreprise", "marché"
]



